version: 2
jobs:
  build:
    docker:
      - image: renewdoit/dotnet-build:0.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - fake
      - run:
          command: |
            paket install
      - save_cache:
          paths:
            - ~/.nuget
          key: fake
      - run:
          command: |
            fake run build.fsx