version: 2
jobs:
  build:
    docker:
      - image: renewdoit/dotnet-build:1.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - fake
      - run:
          command: |
            ~/.dotnet/tools/paket install && ~/.dotnet/tools/fake run build.fsx
      - save_cache:
          paths:
            - ~/.nuget
          key: fake